---
- name: Ensure AKS Cluster exists
  azure.azcollection.azure_rm_aks:
    resource_group: "{{ azure_aks_config.resource_group }}"
    name: "{{ azure_aks_config.cluster.name }}"
    location: "{{ azure_aks_config.location }}"
    dns_prefix: "{{ azure_aks_config.cluster.dns_prefix }}"
    kubernetes_version: "{{ azure_aks_config.cluster.kubernetes_version }}"
    agent_pool_profiles: "{{ azure_aks_config.cluster.agent_pool_profiles }}"
    identity:
      type: SystemAssigned
    api_server_access_profile:
      authorized_ip_ranges:
        - "{{ ansible_controller_public_ip.json.ip }}/32"
    state: present
