---
azure_db_config:
  # Global Deployment settings
  location: "{{ azure_common.location }}"
  resource_group: "rg-{{ azure_resource_base }}"

  # SQL Server Spec and Credentials
  server:
    name: "sql-{{ azure_resource_base }}"
    admin:
      username: "{{ azure_admin.username }}"
      password: "{{ azure_admin.password }}"

  # Database Spec
  database:
    name: "sqldb-{{ azure_resource_base }}"
    sku:
      name: Basic
      tier: Basic
