services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    privileged: true
    devices:
      - "/dev/fuse:/dev/fuse"
    volumes:
      - ..:/workspaces/ansible:cached
      - /var/run/docker.sock:/var/run/docker.sock:z
