---
collections:
  - name: community.docker
    version: '5.2.0'
  - name: ansible.windows
    version: '3.5.0'
  - name: community.windows
    version: '3.1.0'
  - name: azure.azcollection
    version: '3.18.0'
