---
azure_aks_config:
  # Global Deployment settings
  location: "{{ azure_common.location }}"
  resource_group: "rg-{{ azure_resource_base }}"

  # Cluster Spec and Credentials
  cluster:
    name: "aks-{{ azure_resource_base_regional }}"
    dns_prefix: "aks{{ azure_resource_base | replace('-', '') | replace('_', '') }}"
    kubernetes_version: "1.36.0"  # Set to a supported version in the region
    agent_pool_profiles:
      - name: default
        count: 1
        vm_size: Standard_D2_v2
        mode: System
    admin:
      username: "{{ azure_admin.username }}"
      ssh_key: "{{ azure_admin.ssh_key }}"
